### ISSUE TITLE
Add support for other HTTP request methods (POST, PUT, DELETE)

### ISSUE THREAD

**Issue by kffl** [kffl/gocannon#1]
As of version 0.0.1, Gocannon only supports generating HTTP GET requests. A feature allowing for specifying the desired request method of the load test (i.e. `--method=POST`, which would default to `GET` when not provided) should be added.

**Comment by tonyjia87** [comment]
Mabey will add a parameter,ex:

```
-s, --script:      LuaJIT script, see SCRIPTING
```

**Comment by kffl** [comment]
@tonyjia87 I've described the potential support for scripting in a separate issue: #7
