### ISSUE TITLE
Add support for HTTPS?

### ISSUE THREAD

**Issue by jauderho** [kffl/gocannon#4]
It looks like trying to use a HTTPS url returns ErrUnsupportedProtocol at this time.

**Comment by kffl** [comment]
Yes, as of now HTTPS is not supported and the error is thrown intentionally:

https://github.com/kffl/gocannon/blob/68a4fcb00d34404d7a182132218a1530ae95312e/http_test.go#L14-L17

Adding HTTPS support would require some changes to how the fasthttp client instance is created and how the requests are sent. One additional feature that could be added alongside HTTPS support is optional omission of  SSL certificate validation (i.e. to be used in a dev/staging environment in which the load test target uses a self-signed certificate).
